name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run e2e tests for Angular with Playwright and generate HTML report
      - name: Run Playwright e2e tests for Angular
        run: |
          npx nx run swap-ticket-app-e2e:e2e -- --reporter=html
        continue-on-error: false

      # Upload Playwright HTML report as artifact
      - name: Upload Playwright Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/swap-ticket-app-e2e/playwright-report
          retention-days: 7

      # Run e2e tests for API (aanpassen indien nodig voor rapportage)
      - name: Run e2e tests for API
        run: npx nx run swap-ticket-api-e2e:e2e
        continue-on-error: false

      # Deploy API to Heroku
      - name: Deploy API to Heroku
        if: ${{ success() }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote add heroku https://git.heroku.com/${{ env.HEROKU_APP_NAME }}.git
          git push heroku `git subtree split --prefix apps/swap-ticket-api master`:refs/heads/master --force

      # Deploy frontend to Vercel
      - name: Deploy Frontend to Vercel
        if: ${{ success() }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
